site_name: Windoc
copyright: Windoc est sous licence libre CC0
site_url: https://aph11.github.io/windoc/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: orange 
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: orange 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: orange 
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
  language: fr
  logo: img/logo.svg
  favicon: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - search.suggest

nav:
 - Accueil: index.md
 - Habitable:
   - Réglages: habitable/reglages.md
   - Bidouilles:
     - Electricité: habitable/bidouilles/electricite.md
     - Moteur: habitable/bidouilles/moteur.md
   - Cuisine:
     - Recettes: habitable/cuisine/recettes.md
 - Météo: meteo/index.md
 - Théorie: theorie/index.md
 - Voilerie:
   - Materiaux: voilerie/materiaux.md
   - Machines:
     - Introduction: voilerie/machines/introduction.md
     - Entretien: voilerie/machines/entretien.md
     - Réglages: voilerie/machines/reglages.md
 - Windsurf: windsurf/index.md
 - Lexiques:
   - Général: lexiques/general.md
   - Windsurf: lexiques/pav.md
   - Voile traditionnelle: lexiques/voile-trad.md
 - Les ptits guides: les-ptits-guides.md
 - Ressources:
   - Livres: ressources/livres.md
   - Modèles 3D: ressources/cad/modeles-3d.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption

plugins:
  - privacy
  - search
  - tags


